FORMAT: 1A
HOST: http://localhost:5000

# New Document


# Group ineuron

## Update 637cfec14dd7e6b561c2663b [/Update/637cfec14dd7e6b561c2663b]

### put req [PUT]

+ Response 200 
    + Attributes (string)




## Delete 637d01c8fd38984ebd1f826b [/Delete/637d01c8fd38984ebd1f826b]

### delete req [DELETE]

+ Response 200 
    + Attributes (string)




## Add [/Add]

### post req [POST]

+ Response 200 
    + Attributes (string)




## Read [/Read]

### get req [GET]

+ Response 200 
    + Attributes (string)